#define JP_EXCLAMATION    EXCLAMATION       // !
#define JP_DQUOTE         AT                // "
#define JP_HASH           HASH              // #
#define JP_AMPERSAND      CARET             // &
#define JP_QUOTE          AMPERSAND         // '
#define JP_EQUAL          UNDER             // =
#define JP_CARET          EQUAL             // ^
#define JP_YEN            0x89              // ¥
#define JP_DOLLAR         DOLLAR            // $
#define JP_MINUS          MINUS             // -
#define JP_PLUS           COLON             // +
#define JP_PERCENT        PERCENT           // %
#define JP_TILDE          PLUS              // ~
#define JP_PIPE           LS(0x89)          // |
#define JP_AT             LEFT_BRACKET      // @
#define JP_COLON          SINGLE_QUOTE      // :
#define JP_SEMICOLON      SEMICOLON         // ;
#define JP_ASTERISK       DOUBLE_QUOTES     // *
#define JP_BACKQUOTE      LEFT_BRACE        // `
#define JP_BACKSLASH      0x87              // \.
#define JP_UNDERSCORE     LS(0x87)          // _
#define JP_LBRACKET       RIGHT_BRACKET     // [
#define JP_RBRACKET       BACKSLASH         // ]
#define JP_LPAREN         ASTERISK          // (
#define JP_RPAREN         LEFT_PARENTHESIS  // )
#define JP_LBRACE         RIGHT_BRACE       // {
#define JP_RBRACE         PIPE              // }
#define JP_KANA           LANGUAGE_1        // かな
#define JP_EISU           LANGUAGE_2        // 英数
#define JP_ZENHAN         GRAVE             // 半角/全角
#define JP_ZENKAKUHANKAKU GRAVE             // 半角/全角
#define JP_HENKAN         INT_HENKAN        // 変換
#define JP_MUHENKAN       INT_MUHENKAN      // 無変換
#define JP_COMMA          COMMA             // ,
#define JP_LESS_THAN      LESS_THAN         // <
#define JP_LT             LT                // <
#define JP_DOT            DOT               // .
#define JP_GREATER_THAN   GREATER_THAN      // >
#define JP_GT             GT                // >
#define JP_SLASH          SLASH             // /
#define JP_QUESTION       QUESTION          // ?
